// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Mk-V9FzJrsSN8L_nCWzqlv_JnVAllTg',
    appId: '1:958728171639:web:829c4773251a14b4605672',
    messagingSenderId: '958728171639',
    projectId: 'loginandregister01',
    authDomain: 'loginandregister01.firebaseapp.com',
    storageBucket: 'loginandregister01.appspot.com',
    measurementId: 'G-LJRET4FP8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdSqnWJ9-Xg-7uim4cX6KJQaFs1FZ4vGk',
    appId: '1:958728171639:android:5a1061383b948c02605672',
    messagingSenderId: '958728171639',
    projectId: 'loginandregister01',
    storageBucket: 'loginandregister01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAppUWCdEH9hT4TjO6jh0YKAw2JRWfykPg',
    appId: '1:958728171639:ios:abf93ca800b97328605672',
    messagingSenderId: '958728171639',
    projectId: 'loginandregister01',
    storageBucket: 'loginandregister01.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAppUWCdEH9hT4TjO6jh0YKAw2JRWfykPg',
    appId: '1:958728171639:ios:abf93ca800b97328605672',
    messagingSenderId: '958728171639',
    projectId: 'loginandregister01',
    storageBucket: 'loginandregister01.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Mk-V9FzJrsSN8L_nCWzqlv_JnVAllTg',
    appId: '1:958728171639:web:cec2baf8f7583f52605672',
    messagingSenderId: '958728171639',
    projectId: 'loginandregister01',
    authDomain: 'loginandregister01.firebaseapp.com',
    storageBucket: 'loginandregister01.appspot.com',
    measurementId: 'G-Z81CZY57R3',
  );
}
